#!/bin/bash
# use 'touch' to set a stamp older than the first log you want to process, 
# or this will process all logfiles
LOGDIR=/var/local/squid


if [ ${LOGDIR}/access.log.1 -nt /var/lib/squid_import_stamp ] ;
then
    i=2
    while [ ${LOGDIR}/access.log.$i.gz -nt /var/lib/squid_import_stamp ]
    do str="$i,$str" ; i=$((i+1)) 
    done
    tmpfile=$(tempfile -m 640)
    chgrp www-data $tmpfile
    eval zcat -f  ${LOGDIR}/access.log.{{${str::${#str}-1}}.gz,1} > $tmpfile
    /opt/instances/cnx/bin/zopectl run /opt/instances/cnx/Products/RhaptosHitCountTool/Extensions/content_hit_counts.py $tmpfile
    if [ ! $? ]
        then 
            echo "Log import failed! Data at: " $tmpfile
        exit 1 
    else
        rm $tmpfile
        touch /var/lib/squid_import_stamp ; 
        if [ ! $? ]  ;
           then echo "Can't touch timestamp file /var/lib/squid_import_stamp"
        fi
    fi
fi
